### ISSUE TITLE
feedback on semantic label repo

### ISSUE THREAD

**Issue by cabanier** [immersive-web/semantic-labels#1]
/agenda discuss new semantic label repo

**Comment by AdaRoseCannon** [comment]
Was discussed

**Comment by AdaRoseCannon** [comment]
@himorin I've noticed I don't have the ability to remove the agenda label on this repo, could you give me access for that?

**Comment by Yonet** [comment]
@himorin I also can't remove.

**Comment by Yonet** [comment]
@cabanier I believe you've created this repo. Can you give the chairs admin access. Thanks!

**Comment by cabanier** [comment]
> @cabanier I believe you've created this repo. Can you give the chairs admin access. Thanks!

done

**Comment by himorin** [comment]
@AdaRoseCannon @Yonet This repository is not created by me, neither I've requested to configure for IW groups. So permissions are ones set by its creator (as repository owner), I suppose.

**Comment by cabanier** [comment]
> @AdaRoseCannon @Yonet This repository is not created by me, neither I've requested to configure for IW groups. So permissions are ones set by its creator (as repository owner), I suppose.

I'm happy to transfer it to you or if it's more convenient, you can create another repo and I will put the files in there.

**Comment by Yonet** [comment]
@cabanier you can just add us as admin and we can make the updates. Thanks!

**Comment by cabanier** [comment]
> @cabanier you can just add us as admin and we can make the updates. Thanks!

done

**Comment by himorin** [comment]
@Yonet @cabanier For CG repos, chairs and core editors are configured as Admin via team permission, no need to add additional configuration.
